### ISSUE TITLE
WIn-build Actions are expired - no downloads of any working that newer than 2.0.0rc8

### ISSUE THREAD

**Issue by DaLiV** [DivingDuck/Printrun#23]
wanted to try latest versions for windows 
- latest throw exception
- but all other previous builds are downloads "expired"

**Comment by DivingDuck** [comment]
Multiple post of  issue with https://github.com/kliment/Printrun/issues/1295

This branch have no official releases. Here are only my development releases as artifacts available. Actually you can find an access point in the Wiki here: 
https://github.com/DivingDuck/Printrun/wiki/My-latest-development-version-build-with-github-workflow

We should handle this issue in one location only. Please see my answer in https://github.com/kliment/Printrun/issues/1295 for next steps.

I will close the issue here to avoid cross postings.
